image: Visual Studio 2015
platform: x64
environment:
  nodejs_version: 6
services:
  - mysql
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: npm install
test_script:
  - npm test
build: off
