// flow-typed signature: 19493a4f3f92bb510fc626bf1e07c299
// flow-typed version: <<STUB>>/acorn_v4.0.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'acorn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'acorn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'acorn/dist/acorn_loose.es' {
  declare module.exports: any;
}

declare module 'acorn/dist/acorn_loose' {
  declare module.exports: any;
}

declare module 'acorn/dist/acorn.es' {
  declare module.exports: any;
}

declare module 'acorn/dist/acorn' {
  declare module.exports: any;
}

declare module 'acorn/dist/walk.es' {
  declare module.exports: any;
}

declare module 'acorn/dist/walk' {
  declare module.exports: any;
}

declare module 'acorn/src/bin/acorn' {
  declare module.exports: any;
}

declare module 'acorn/src/expression' {
  declare module.exports: any;
}

declare module 'acorn/src/identifier' {
  declare module.exports: any;
}

declare module 'acorn/src/index' {
  declare module.exports: any;
}

declare module 'acorn/src/location' {
  declare module.exports: any;
}

declare module 'acorn/src/locutil' {
  declare module.exports: any;
}

declare module 'acorn/src/loose/expression' {
  declare module.exports: any;
}

declare module 'acorn/src/loose/index' {
  declare module.exports: any;
}

declare module 'acorn/src/loose/parseutil' {
  declare module.exports: any;
}

declare module 'acorn/src/loose/state' {
  declare module.exports: any;
}

declare module 'acorn/src/loose/statement' {
  declare module.exports: any;
}

declare module 'acorn/src/loose/tokenize' {
  declare module.exports: any;
}

declare module 'acorn/src/lval' {
  declare module.exports: any;
}

declare module 'acorn/src/node' {
  declare module.exports: any;
}

declare module 'acorn/src/options' {
  declare module.exports: any;
}

declare module 'acorn/src/parseutil' {
  declare module.exports: any;
}

declare module 'acorn/src/state' {
  declare module.exports: any;
}

declare module 'acorn/src/statement' {
  declare module.exports: any;
}

declare module 'acorn/src/tokencontext' {
  declare module.exports: any;
}

declare module 'acorn/src/tokenize' {
  declare module.exports: any;
}

declare module 'acorn/src/tokentype' {
  declare module.exports: any;
}

declare module 'acorn/src/util' {
  declare module.exports: any;
}

declare module 'acorn/src/walk/index' {
  declare module.exports: any;
}

declare module 'acorn/src/whitespace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'acorn/dist/acorn_loose.es.js' {
  declare module.exports: $Exports<'acorn/dist/acorn_loose.es'>;
}
declare module 'acorn/dist/acorn_loose.js' {
  declare module.exports: $Exports<'acorn/dist/acorn_loose'>;
}
declare module 'acorn/dist/acorn.es.js' {
  declare module.exports: $Exports<'acorn/dist/acorn.es'>;
}
declare module 'acorn/dist/acorn.js' {
  declare module.exports: $Exports<'acorn/dist/acorn'>;
}
declare module 'acorn/dist/walk.es.js' {
  declare module.exports: $Exports<'acorn/dist/walk.es'>;
}
declare module 'acorn/dist/walk.js' {
  declare module.exports: $Exports<'acorn/dist/walk'>;
}
declare module 'acorn/src/bin/acorn.js' {
  declare module.exports: $Exports<'acorn/src/bin/acorn'>;
}
declare module 'acorn/src/expression.js' {
  declare module.exports: $Exports<'acorn/src/expression'>;
}
declare module 'acorn/src/identifier.js' {
  declare module.exports: $Exports<'acorn/src/identifier'>;
}
declare module 'acorn/src/index.js' {
  declare module.exports: $Exports<'acorn/src/index'>;
}
declare module 'acorn/src/location.js' {
  declare module.exports: $Exports<'acorn/src/location'>;
}
declare module 'acorn/src/locutil.js' {
  declare module.exports: $Exports<'acorn/src/locutil'>;
}
declare module 'acorn/src/loose/expression.js' {
  declare module.exports: $Exports<'acorn/src/loose/expression'>;
}
declare module 'acorn/src/loose/index.js' {
  declare module.exports: $Exports<'acorn/src/loose/index'>;
}
declare module 'acorn/src/loose/parseutil.js' {
  declare module.exports: $Exports<'acorn/src/loose/parseutil'>;
}
declare module 'acorn/src/loose/state.js' {
  declare module.exports: $Exports<'acorn/src/loose/state'>;
}
declare module 'acorn/src/loose/statement.js' {
  declare module.exports: $Exports<'acorn/src/loose/statement'>;
}
declare module 'acorn/src/loose/tokenize.js' {
  declare module.exports: $Exports<'acorn/src/loose/tokenize'>;
}
declare module 'acorn/src/lval.js' {
  declare module.exports: $Exports<'acorn/src/lval'>;
}
declare module 'acorn/src/node.js' {
  declare module.exports: $Exports<'acorn/src/node'>;
}
declare module 'acorn/src/options.js' {
  declare module.exports: $Exports<'acorn/src/options'>;
}
declare module 'acorn/src/parseutil.js' {
  declare module.exports: $Exports<'acorn/src/parseutil'>;
}
declare module 'acorn/src/state.js' {
  declare module.exports: $Exports<'acorn/src/state'>;
}
declare module 'acorn/src/statement.js' {
  declare module.exports: $Exports<'acorn/src/statement'>;
}
declare module 'acorn/src/tokencontext.js' {
  declare module.exports: $Exports<'acorn/src/tokencontext'>;
}
declare module 'acorn/src/tokenize.js' {
  declare module.exports: $Exports<'acorn/src/tokenize'>;
}
declare module 'acorn/src/tokentype.js' {
  declare module.exports: $Exports<'acorn/src/tokentype'>;
}
declare module 'acorn/src/util.js' {
  declare module.exports: $Exports<'acorn/src/util'>;
}
declare module 'acorn/src/walk/index.js' {
  declare module.exports: $Exports<'acorn/src/walk/index'>;
}
declare module 'acorn/src/whitespace.js' {
  declare module.exports: $Exports<'acorn/src/whitespace'>;
}
