// flow-typed signature: 8143c2307eed0a1790454d27919d1678
// flow-typed version: <<STUB>>/cash_v0.8.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cash/bin/alias' {
  declare module.exports: any;
}

declare module 'cash/bin/cash' {
  declare module.exports: any;
}

declare module 'cash/bin/cat' {
  declare module.exports: any;
}

declare module 'cash/bin/cd' {
  declare module.exports: any;
}

declare module 'cash/bin/clear' {
  declare module.exports: any;
}

declare module 'cash/bin/cp' {
  declare module.exports: any;
}

declare module 'cash/bin/echo' {
  declare module.exports: any;
}

declare module 'cash/bin/export' {
  declare module.exports: any;
}

declare module 'cash/bin/false' {
  declare module.exports: any;
}

declare module 'cash/bin/grep' {
  declare module.exports: any;
}

declare module 'cash/bin/head' {
  declare module.exports: any;
}

declare module 'cash/bin/kill' {
  declare module.exports: any;
}

declare module 'cash/bin/less' {
  declare module.exports: any;
}

declare module 'cash/bin/ls' {
  declare module.exports: any;
}

declare module 'cash/bin/mkdir' {
  declare module.exports: any;
}

declare module 'cash/bin/mv' {
  declare module.exports: any;
}

declare module 'cash/bin/parser' {
  declare module.exports: any;
}

declare module 'cash/bin/pwd' {
  declare module.exports: any;
}

declare module 'cash/bin/rm' {
  declare module.exports: any;
}

declare module 'cash/bin/sort' {
  declare module.exports: any;
}

declare module 'cash/bin/source' {
  declare module.exports: any;
}

declare module 'cash/bin/tail' {
  declare module.exports: any;
}

declare module 'cash/bin/touch' {
  declare module.exports: any;
}

declare module 'cash/bin/true' {
  declare module.exports: any;
}

declare module 'cash/bin/unalias' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/alias' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/boilerplate' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/cat' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/cd' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/clear' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/cp' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/echo' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/export' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/false' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/grep' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/head' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/kill' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/less' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/ls' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/mkdir' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/mv' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/pwd' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/rm' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/sort' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/source' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/tail' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/touch' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/true' {
  declare module.exports: any;
}

declare module 'cash/dist/commands/unalias' {
  declare module.exports: any;
}

declare module 'cash/dist/delimiter' {
  declare module.exports: any;
}

declare module 'cash/dist/help' {
  declare module.exports: any;
}

declare module 'cash/dist/help/alias' {
  declare module.exports: any;
}

declare module 'cash/dist/help/cat' {
  declare module.exports: any;
}

declare module 'cash/dist/help/cd' {
  declare module.exports: any;
}

declare module 'cash/dist/help/clear' {
  declare module.exports: any;
}

declare module 'cash/dist/help/cp' {
  declare module.exports: any;
}

declare module 'cash/dist/help/echo' {
  declare module.exports: any;
}

declare module 'cash/dist/help/export' {
  declare module.exports: any;
}

declare module 'cash/dist/help/false' {
  declare module.exports: any;
}

declare module 'cash/dist/help/grep' {
  declare module.exports: any;
}

declare module 'cash/dist/help/head' {
  declare module.exports: any;
}

declare module 'cash/dist/help/kill' {
  declare module.exports: any;
}

declare module 'cash/dist/help/ls' {
  declare module.exports: any;
}

declare module 'cash/dist/help/mkdir' {
  declare module.exports: any;
}

declare module 'cash/dist/help/mv' {
  declare module.exports: any;
}

declare module 'cash/dist/help/pwd' {
  declare module.exports: any;
}

declare module 'cash/dist/help/rm' {
  declare module.exports: any;
}

declare module 'cash/dist/help/sort' {
  declare module.exports: any;
}

declare module 'cash/dist/help/source' {
  declare module.exports: any;
}

declare module 'cash/dist/help/tail' {
  declare module.exports: any;
}

declare module 'cash/dist/help/touch' {
  declare module.exports: any;
}

declare module 'cash/dist/help/true' {
  declare module.exports: any;
}

declare module 'cash/dist/help/unalias' {
  declare module.exports: any;
}

declare module 'cash/dist/index' {
  declare module.exports: any;
}

declare module 'cash/dist/lib/sugar' {
  declare module.exports: any;
}

declare module 'cash/dist/preparser' {
  declare module.exports: any;
}

declare module 'cash/dist/util/colorFile' {
  declare module.exports: any;
}

declare module 'cash/dist/util/columnify' {
  declare module.exports: any;
}

declare module 'cash/dist/util/converter.date' {
  declare module.exports: any;
}

declare module 'cash/dist/util/converter.path' {
  declare module.exports: any;
}

declare module 'cash/dist/util/converter.permissions' {
  declare module.exports: any;
}

declare module 'cash/dist/util/expand' {
  declare module.exports: any;
}

declare module 'cash/dist/util/fetch' {
  declare module.exports: any;
}

declare module 'cash/dist/util/fileFromPath' {
  declare module.exports: any;
}

declare module 'cash/dist/util/intercept' {
  declare module.exports: any;
}

declare module 'cash/dist/util/interfacer' {
  declare module.exports: any;
}

declare module 'cash/dist/util/lpad' {
  declare module.exports: any;
}

declare module 'cash/dist/util/pad' {
  declare module.exports: any;
}

declare module 'cash/dist/util/stripAnsi' {
  declare module.exports: any;
}

declare module 'cash/dist/util/unlinkSync' {
  declare module.exports: any;
}

declare module 'cash/dist/util/walkDir' {
  declare module.exports: any;
}

declare module 'cash/dist/util/walkDirRecursive' {
  declare module.exports: any;
}

declare module 'cash/dist/windows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cash/bin/alias.js' {
  declare module.exports: $Exports<'cash/bin/alias'>;
}
declare module 'cash/bin/cash.js' {
  declare module.exports: $Exports<'cash/bin/cash'>;
}
declare module 'cash/bin/cat.js' {
  declare module.exports: $Exports<'cash/bin/cat'>;
}
declare module 'cash/bin/cd.js' {
  declare module.exports: $Exports<'cash/bin/cd'>;
}
declare module 'cash/bin/clear.js' {
  declare module.exports: $Exports<'cash/bin/clear'>;
}
declare module 'cash/bin/cp.js' {
  declare module.exports: $Exports<'cash/bin/cp'>;
}
declare module 'cash/bin/echo.js' {
  declare module.exports: $Exports<'cash/bin/echo'>;
}
declare module 'cash/bin/export.js' {
  declare module.exports: $Exports<'cash/bin/export'>;
}
declare module 'cash/bin/false.js' {
  declare module.exports: $Exports<'cash/bin/false'>;
}
declare module 'cash/bin/grep.js' {
  declare module.exports: $Exports<'cash/bin/grep'>;
}
declare module 'cash/bin/head.js' {
  declare module.exports: $Exports<'cash/bin/head'>;
}
declare module 'cash/bin/kill.js' {
  declare module.exports: $Exports<'cash/bin/kill'>;
}
declare module 'cash/bin/less.js' {
  declare module.exports: $Exports<'cash/bin/less'>;
}
declare module 'cash/bin/ls.js' {
  declare module.exports: $Exports<'cash/bin/ls'>;
}
declare module 'cash/bin/mkdir.js' {
  declare module.exports: $Exports<'cash/bin/mkdir'>;
}
declare module 'cash/bin/mv.js' {
  declare module.exports: $Exports<'cash/bin/mv'>;
}
declare module 'cash/bin/parser.js' {
  declare module.exports: $Exports<'cash/bin/parser'>;
}
declare module 'cash/bin/pwd.js' {
  declare module.exports: $Exports<'cash/bin/pwd'>;
}
declare module 'cash/bin/rm.js' {
  declare module.exports: $Exports<'cash/bin/rm'>;
}
declare module 'cash/bin/sort.js' {
  declare module.exports: $Exports<'cash/bin/sort'>;
}
declare module 'cash/bin/source.js' {
  declare module.exports: $Exports<'cash/bin/source'>;
}
declare module 'cash/bin/tail.js' {
  declare module.exports: $Exports<'cash/bin/tail'>;
}
declare module 'cash/bin/touch.js' {
  declare module.exports: $Exports<'cash/bin/touch'>;
}
declare module 'cash/bin/true.js' {
  declare module.exports: $Exports<'cash/bin/true'>;
}
declare module 'cash/bin/unalias.js' {
  declare module.exports: $Exports<'cash/bin/unalias'>;
}
declare module 'cash/dist/commands/alias.js' {
  declare module.exports: $Exports<'cash/dist/commands/alias'>;
}
declare module 'cash/dist/commands/boilerplate.js' {
  declare module.exports: $Exports<'cash/dist/commands/boilerplate'>;
}
declare module 'cash/dist/commands/cat.js' {
  declare module.exports: $Exports<'cash/dist/commands/cat'>;
}
declare module 'cash/dist/commands/cd.js' {
  declare module.exports: $Exports<'cash/dist/commands/cd'>;
}
declare module 'cash/dist/commands/clear.js' {
  declare module.exports: $Exports<'cash/dist/commands/clear'>;
}
declare module 'cash/dist/commands/cp.js' {
  declare module.exports: $Exports<'cash/dist/commands/cp'>;
}
declare module 'cash/dist/commands/echo.js' {
  declare module.exports: $Exports<'cash/dist/commands/echo'>;
}
declare module 'cash/dist/commands/export.js' {
  declare module.exports: $Exports<'cash/dist/commands/export'>;
}
declare module 'cash/dist/commands/false.js' {
  declare module.exports: $Exports<'cash/dist/commands/false'>;
}
declare module 'cash/dist/commands/grep.js' {
  declare module.exports: $Exports<'cash/dist/commands/grep'>;
}
declare module 'cash/dist/commands/head.js' {
  declare module.exports: $Exports<'cash/dist/commands/head'>;
}
declare module 'cash/dist/commands/kill.js' {
  declare module.exports: $Exports<'cash/dist/commands/kill'>;
}
declare module 'cash/dist/commands/less.js' {
  declare module.exports: $Exports<'cash/dist/commands/less'>;
}
declare module 'cash/dist/commands/ls.js' {
  declare module.exports: $Exports<'cash/dist/commands/ls'>;
}
declare module 'cash/dist/commands/mkdir.js' {
  declare module.exports: $Exports<'cash/dist/commands/mkdir'>;
}
declare module 'cash/dist/commands/mv.js' {
  declare module.exports: $Exports<'cash/dist/commands/mv'>;
}
declare module 'cash/dist/commands/pwd.js' {
  declare module.exports: $Exports<'cash/dist/commands/pwd'>;
}
declare module 'cash/dist/commands/rm.js' {
  declare module.exports: $Exports<'cash/dist/commands/rm'>;
}
declare module 'cash/dist/commands/sort.js' {
  declare module.exports: $Exports<'cash/dist/commands/sort'>;
}
declare module 'cash/dist/commands/source.js' {
  declare module.exports: $Exports<'cash/dist/commands/source'>;
}
declare module 'cash/dist/commands/tail.js' {
  declare module.exports: $Exports<'cash/dist/commands/tail'>;
}
declare module 'cash/dist/commands/touch.js' {
  declare module.exports: $Exports<'cash/dist/commands/touch'>;
}
declare module 'cash/dist/commands/true.js' {
  declare module.exports: $Exports<'cash/dist/commands/true'>;
}
declare module 'cash/dist/commands/unalias.js' {
  declare module.exports: $Exports<'cash/dist/commands/unalias'>;
}
declare module 'cash/dist/delimiter.js' {
  declare module.exports: $Exports<'cash/dist/delimiter'>;
}
declare module 'cash/dist/help.js' {
  declare module.exports: $Exports<'cash/dist/help'>;
}
declare module 'cash/dist/help/alias.js' {
  declare module.exports: $Exports<'cash/dist/help/alias'>;
}
declare module 'cash/dist/help/cat.js' {
  declare module.exports: $Exports<'cash/dist/help/cat'>;
}
declare module 'cash/dist/help/cd.js' {
  declare module.exports: $Exports<'cash/dist/help/cd'>;
}
declare module 'cash/dist/help/clear.js' {
  declare module.exports: $Exports<'cash/dist/help/clear'>;
}
declare module 'cash/dist/help/cp.js' {
  declare module.exports: $Exports<'cash/dist/help/cp'>;
}
declare module 'cash/dist/help/echo.js' {
  declare module.exports: $Exports<'cash/dist/help/echo'>;
}
declare module 'cash/dist/help/export.js' {
  declare module.exports: $Exports<'cash/dist/help/export'>;
}
declare module 'cash/dist/help/false.js' {
  declare module.exports: $Exports<'cash/dist/help/false'>;
}
declare module 'cash/dist/help/grep.js' {
  declare module.exports: $Exports<'cash/dist/help/grep'>;
}
declare module 'cash/dist/help/head.js' {
  declare module.exports: $Exports<'cash/dist/help/head'>;
}
declare module 'cash/dist/help/kill.js' {
  declare module.exports: $Exports<'cash/dist/help/kill'>;
}
declare module 'cash/dist/help/ls.js' {
  declare module.exports: $Exports<'cash/dist/help/ls'>;
}
declare module 'cash/dist/help/mkdir.js' {
  declare module.exports: $Exports<'cash/dist/help/mkdir'>;
}
declare module 'cash/dist/help/mv.js' {
  declare module.exports: $Exports<'cash/dist/help/mv'>;
}
declare module 'cash/dist/help/pwd.js' {
  declare module.exports: $Exports<'cash/dist/help/pwd'>;
}
declare module 'cash/dist/help/rm.js' {
  declare module.exports: $Exports<'cash/dist/help/rm'>;
}
declare module 'cash/dist/help/sort.js' {
  declare module.exports: $Exports<'cash/dist/help/sort'>;
}
declare module 'cash/dist/help/source.js' {
  declare module.exports: $Exports<'cash/dist/help/source'>;
}
declare module 'cash/dist/help/tail.js' {
  declare module.exports: $Exports<'cash/dist/help/tail'>;
}
declare module 'cash/dist/help/touch.js' {
  declare module.exports: $Exports<'cash/dist/help/touch'>;
}
declare module 'cash/dist/help/true.js' {
  declare module.exports: $Exports<'cash/dist/help/true'>;
}
declare module 'cash/dist/help/unalias.js' {
  declare module.exports: $Exports<'cash/dist/help/unalias'>;
}
declare module 'cash/dist/index.js' {
  declare module.exports: $Exports<'cash/dist/index'>;
}
declare module 'cash/dist/lib/sugar.js' {
  declare module.exports: $Exports<'cash/dist/lib/sugar'>;
}
declare module 'cash/dist/preparser.js' {
  declare module.exports: $Exports<'cash/dist/preparser'>;
}
declare module 'cash/dist/util/colorFile.js' {
  declare module.exports: $Exports<'cash/dist/util/colorFile'>;
}
declare module 'cash/dist/util/columnify.js' {
  declare module.exports: $Exports<'cash/dist/util/columnify'>;
}
declare module 'cash/dist/util/converter.date.js' {
  declare module.exports: $Exports<'cash/dist/util/converter.date'>;
}
declare module 'cash/dist/util/converter.path.js' {
  declare module.exports: $Exports<'cash/dist/util/converter.path'>;
}
declare module 'cash/dist/util/converter.permissions.js' {
  declare module.exports: $Exports<'cash/dist/util/converter.permissions'>;
}
declare module 'cash/dist/util/expand.js' {
  declare module.exports: $Exports<'cash/dist/util/expand'>;
}
declare module 'cash/dist/util/fetch.js' {
  declare module.exports: $Exports<'cash/dist/util/fetch'>;
}
declare module 'cash/dist/util/fileFromPath.js' {
  declare module.exports: $Exports<'cash/dist/util/fileFromPath'>;
}
declare module 'cash/dist/util/intercept.js' {
  declare module.exports: $Exports<'cash/dist/util/intercept'>;
}
declare module 'cash/dist/util/interfacer.js' {
  declare module.exports: $Exports<'cash/dist/util/interfacer'>;
}
declare module 'cash/dist/util/lpad.js' {
  declare module.exports: $Exports<'cash/dist/util/lpad'>;
}
declare module 'cash/dist/util/pad.js' {
  declare module.exports: $Exports<'cash/dist/util/pad'>;
}
declare module 'cash/dist/util/stripAnsi.js' {
  declare module.exports: $Exports<'cash/dist/util/stripAnsi'>;
}
declare module 'cash/dist/util/unlinkSync.js' {
  declare module.exports: $Exports<'cash/dist/util/unlinkSync'>;
}
declare module 'cash/dist/util/walkDir.js' {
  declare module.exports: $Exports<'cash/dist/util/walkDir'>;
}
declare module 'cash/dist/util/walkDirRecursive.js' {
  declare module.exports: $Exports<'cash/dist/util/walkDirRecursive'>;
}
declare module 'cash/dist/windows.js' {
  declare module.exports: $Exports<'cash/dist/windows'>;
}
