// flow-typed signature: 0759cc3cd9396c83cc6ec9395aaebfe3
// flow-typed version: <<STUB>>/eol_v0.5.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eol/converter' {
  declare module.exports: any;
}

declare module 'eol/eol' {
  declare module.exports: any;
}

declare module 'eol/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eol/converter.js' {
  declare module.exports: $Exports<'eol/converter'>;
}
declare module 'eol/eol.js' {
  declare module.exports: $Exports<'eol/eol'>;
}
declare module 'eol/test.js' {
  declare module.exports: $Exports<'eol/test'>;
}
