// flow-typed signature: 76dc560e58e6925bd213b3197a333685
// flow-typed version: <<STUB>>/magic-string_v0.19.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'magic-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'magic-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'magic-string/dist/magic-string.cjs' {
  declare module.exports: any;
}

declare module 'magic-string/dist/magic-string.es' {
  declare module.exports: any;
}

declare module 'magic-string/dist/magic-string.umd' {
  declare module.exports: any;
}

declare module 'magic-string/src/Bundle' {
  declare module.exports: any;
}

declare module 'magic-string/src/Chunk' {
  declare module.exports: any;
}

declare module 'magic-string/src/index-legacy' {
  declare module.exports: any;
}

declare module 'magic-string/src/index' {
  declare module.exports: any;
}

declare module 'magic-string/src/MagicString' {
  declare module.exports: any;
}

declare module 'magic-string/src/utils/btoa' {
  declare module.exports: any;
}

declare module 'magic-string/src/utils/getLocator' {
  declare module.exports: any;
}

declare module 'magic-string/src/utils/getRelativePath' {
  declare module.exports: any;
}

declare module 'magic-string/src/utils/guessIndent' {
  declare module.exports: any;
}

declare module 'magic-string/src/utils/hasOwnProp' {
  declare module.exports: any;
}

declare module 'magic-string/src/utils/isObject' {
  declare module.exports: any;
}

declare module 'magic-string/src/utils/Mappings' {
  declare module.exports: any;
}

declare module 'magic-string/src/utils/SourceMap' {
  declare module.exports: any;
}

declare module 'magic-string/src/utils/Stats' {
  declare module.exports: any;
}

// Filename aliases
declare module 'magic-string/dist/magic-string.cjs.js' {
  declare module.exports: $Exports<'magic-string/dist/magic-string.cjs'>;
}
declare module 'magic-string/dist/magic-string.es.js' {
  declare module.exports: $Exports<'magic-string/dist/magic-string.es'>;
}
declare module 'magic-string/dist/magic-string.umd.js' {
  declare module.exports: $Exports<'magic-string/dist/magic-string.umd'>;
}
declare module 'magic-string/src/Bundle.js' {
  declare module.exports: $Exports<'magic-string/src/Bundle'>;
}
declare module 'magic-string/src/Chunk.js' {
  declare module.exports: $Exports<'magic-string/src/Chunk'>;
}
declare module 'magic-string/src/index-legacy.js' {
  declare module.exports: $Exports<'magic-string/src/index-legacy'>;
}
declare module 'magic-string/src/index.js' {
  declare module.exports: $Exports<'magic-string/src/index'>;
}
declare module 'magic-string/src/MagicString.js' {
  declare module.exports: $Exports<'magic-string/src/MagicString'>;
}
declare module 'magic-string/src/utils/btoa.js' {
  declare module.exports: $Exports<'magic-string/src/utils/btoa'>;
}
declare module 'magic-string/src/utils/getLocator.js' {
  declare module.exports: $Exports<'magic-string/src/utils/getLocator'>;
}
declare module 'magic-string/src/utils/getRelativePath.js' {
  declare module.exports: $Exports<'magic-string/src/utils/getRelativePath'>;
}
declare module 'magic-string/src/utils/guessIndent.js' {
  declare module.exports: $Exports<'magic-string/src/utils/guessIndent'>;
}
declare module 'magic-string/src/utils/hasOwnProp.js' {
  declare module.exports: $Exports<'magic-string/src/utils/hasOwnProp'>;
}
declare module 'magic-string/src/utils/isObject.js' {
  declare module.exports: $Exports<'magic-string/src/utils/isObject'>;
}
declare module 'magic-string/src/utils/Mappings.js' {
  declare module.exports: $Exports<'magic-string/src/utils/Mappings'>;
}
declare module 'magic-string/src/utils/SourceMap.js' {
  declare module.exports: $Exports<'magic-string/src/utils/SourceMap'>;
}
declare module 'magic-string/src/utils/Stats.js' {
  declare module.exports: $Exports<'magic-string/src/utils/Stats'>;
}
