// flow-typed signature: 2141aa7641e89cdfd1a28c814109e6e7
// flow-typed version: <<STUB>>/release_v1.1.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'release' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'release/bin/preinstall' {
  declare module.exports: any;
}

declare module 'release/bin/release' {
  declare module.exports: any;
}

declare module 'release/lib/changelog' {
  declare module.exports: any;
}

declare module 'release/lib/choices' {
  declare module.exports: any;
}

declare module 'release/lib/clean-title' {
  declare module.exports: any;
}

declare module 'release/lib/commits' {
  declare module.exports: any;
}

declare module 'release/lib/connect' {
  declare module.exports: any;
}

declare module 'release/lib/credits' {
  declare module.exports: any;
}

declare module 'release/lib/definitions' {
  declare module.exports: any;
}

declare module 'release/lib/group' {
  declare module.exports: any;
}

declare module 'release/lib/pick-commit' {
  declare module.exports: any;
}

declare module 'release/lib/repo' {
  declare module.exports: any;
}

declare module 'release/lib/spinner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'release/bin/preinstall.js' {
  declare module.exports: $Exports<'release/bin/preinstall'>;
}
declare module 'release/bin/release.js' {
  declare module.exports: $Exports<'release/bin/release'>;
}
declare module 'release/lib/changelog.js' {
  declare module.exports: $Exports<'release/lib/changelog'>;
}
declare module 'release/lib/choices.js' {
  declare module.exports: $Exports<'release/lib/choices'>;
}
declare module 'release/lib/clean-title.js' {
  declare module.exports: $Exports<'release/lib/clean-title'>;
}
declare module 'release/lib/commits.js' {
  declare module.exports: $Exports<'release/lib/commits'>;
}
declare module 'release/lib/connect.js' {
  declare module.exports: $Exports<'release/lib/connect'>;
}
declare module 'release/lib/credits.js' {
  declare module.exports: $Exports<'release/lib/credits'>;
}
declare module 'release/lib/definitions.js' {
  declare module.exports: $Exports<'release/lib/definitions'>;
}
declare module 'release/lib/group.js' {
  declare module.exports: $Exports<'release/lib/group'>;
}
declare module 'release/lib/pick-commit.js' {
  declare module.exports: $Exports<'release/lib/pick-commit'>;
}
declare module 'release/lib/repo.js' {
  declare module.exports: $Exports<'release/lib/repo'>;
}
declare module 'release/lib/spinner.js' {
  declare module.exports: $Exports<'release/lib/spinner'>;
}
